### ISSUE TITLE
the class was then set on the table cell instead of on the table.

### ISSUE THREAD

**Issue by thomasdumm** [pressbooks/pressbooks-table-classes#1]
I defined the class "wide" as a table class in the plugin settings, but the class was then set on the table cell instead of on the table. No table cell and table row classes were defined on the plugin settings.

#### Book Info

Book ID: 46
Book URL: https://delivros.pressbooks.pub/test/
Book Privacy: Public

#### Browser

Platform: OS X
Browser Name: Firefox
Browser Version: 61.0
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:61.0) Gecko/20100101 Firefox/61.0

#### WordPress Configuration

Network URL: http://delivros.pressbooks.pub/
Network Type: Subdirectory
Version: 4.9.7
Language: en_US
WP_ENV: production
WP_DEBUG: Disabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 5.4.5
Book Theme: McLuhan
Book Theme Version: 2.4.3
Root Theme: Pressbooks Publisher
Root Theme Version: 3.1.4

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Not Installed
Saxon-HE: Installed

#### Must-Use Plugins

Bedrock Autoloader: 1.0.0
hm-autoloader.php: n/a
telemetry.php: n/a

#### Network Active Plugins

Hypothesis: 0.5.0
Pressbooks: 5.4.5
Pressbooks Cover Generator: 2.4.0
Pressbooks Stats: 1.4.1
Pressbooks Whitelabel: 1.2.0
Redis Object Cache: 1.3.8
User Activation Keys: 4.6

#### Book Active Plugins

Pressbooks Table Classes: 1.0.0

#### Inactive Plugins

Akismet Anti-Spam: 3.3.4
Pressbooks BISAC: 2.0.0

#### Server Configuration

PHP Version: 7.1.13-1+ubuntu16.04.1+deb.sury.org+1
MySQL Version: 5.5.5
Webserver Info: nginx/1.13.6

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 256M
Upload Max Size: 25M
Post Max Size: 25M
Upload Max Filesize: 25M
Time Limit: 120
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: N/A

#### PHP Extensions

OPcache: Zend
XDebug: Disabled
cURL: Supported
cURL Version: 7.47.0
imagick: Not Installed
xsl: Installed

**Comment by greatislander** [comment]
We are no longer supporting and maintaining this plugin.
